## Tensorflow

### Cơ bản

In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np

Instructions for updating:
non-resource variables are not supported in the long term


#### constant

In [2]:
x = tf.constant([[1., 2., 3.],
                 [4., 5., 6.],
                 [7., 8., 9]])
ses = tf.Session()
print(ses.run(x))
print(".....................................................................")
print(x)
print(".....................................................................")
print(x.shape)
print(".....................................................................")
print(x.dtype)
print(".....................................................................")
y = tf.constant(1)
print(y)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
.....................................................................
Tensor("Const:0", shape=(3, 3), dtype=float32)
.....................................................................
(3, 3)
.....................................................................
<dtype: 'float32'>
.....................................................................
Tensor("Const_1:0", shape=(), dtype=int32)


In [3]:
print(ses.run(x+x))
print(".....................................................................")
print(ses.run(5 * y))
print(".....................................................................")
print(ses.run(x @ tf.transpose(x)))
print(".....................................................................")
print(ses.run(tf.concat([x, x, x], axis=0)))
print(".....................................................................")
print(ses.run(tf.nn.softmax(x, axis=-1))) #hàm softmax
print(".....................................................................")
print(ses.run(tf.reduce_sum(x))) #tổng các phần tử

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
.....................................................................
5
.....................................................................
[[ 14.  32.  50.]
 [ 32.  77. 122.]
 [ 50. 122. 194.]]
.....................................................................
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]
 [1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]
 [1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
.....................................................................
[[0.09003057 0.24472848 0.66524094]
 [0.09003057 0.24472848 0.66524094]
 [0.09003057 0.24472848 0.66524094]]
.....................................................................
45.0


#### placeholder ~ use for input

In [4]:
p1 = tf.placeholder(dtype = tf.float32)
p2 = tf.placeholder(dtype = tf.float32)

In [5]:
# Asign 

o_add = p1 + p2
o_mul = p1 * p2


In [6]:
print(o_add)

Tensor("add_1:0", dtype=float32)


In [7]:
d_values = {
    p1: 7,
    p2: 10
}
see = tf.Session()
see.run(o_add,feed_dict = d_values)

17.0

In [8]:
see.run([o_add,o_mul], feed_dict = d_values)

[17.0, 70.0]

#### variables

In [9]:
var_1 = tf.Variable(name='var_1',initial_value = 7)
var_2 = tf.Variable(name='var_2',initial_value = 10)

In [10]:
see.run(var_1.initializer)

In [11]:
see.run(var_1)

7

In [12]:
tf.global_variables_initializer().run(session = see)

In [13]:
see.run(var_2)

10